---
- name: rsyncd | create log directory
  become: yes
  file:
    path: /var/log/rsync
    mode: '0750'
    state: directory

- name: Create a file for logging
  file:
    path: "/var/log/rsync/{{ item.name }}.log"
    state: touch
    access_time: preserve
    mode: '0640'
    owner: root
    group: root
  loop: "{{ rsync_server_shares }}"

- name: rsyncd | configure logrotate
  become: yes
  template:
    backup: no
    dest: /etc/logrotate.d/rsyncd
    src: logrotated-rsyncd.j2
    owner: root
    group: root
    mode: 0440
  tags:
    - rsyncd-logrotate

- name: remove old logrotate file
  become: yes
  file:
    path: /etc/logrotate.d/rsync
    state: absent
  tags:
    - rsyncd-logrotate

