---
# tasks file for rsync-server

- name: rsyncd | install rsync
  become: yes
  yum:
    pkg: rsync
    state: present

- name: rsyncd | create log directory
  become: yes
  file:
    path: /var/log/rsync
    mode: '0750'
    state: directory

- name: rsyncd | configure shares
  become: yes
  template:
    backup: yes
    dest: /etc/rsyncd.conf
    src: etc-rsyncd-conf.j2
    mode: '0400'
    owner: root
    group: root
  tags:
    - rsyncd.conf

- name: Create a directory if it does not exist
  file:
    path: "{{ item.path }}"
    state: directory
    #mode: '0755'
    #recurse: yes
    owner: "{{ item.uid | default('apache') }}"
    group: "{{ item.gid | default('apache') }}"
  loop: "{{ rsync_server_shares }}"
  tags:
    - dirs
    - rsyncd-dirs
    - rsyncd-logs


- name: Create a file for logging
  file:
    path: "/var/log/rsync/{{ share.name }}.log"
    state: touch
    access_time: preserve
    mode: '0640'
    owner: root
    group: root
  loop: "{{ rsync_server_shares }}"
  tags:
    - rsyncd-logs

- name: rsyncd | configure logrotate
  become: yes
  template:
    backup: no
    dest: /etc/logrotate.d/rsyncd
    src: logrotated-rsyncd.j2
  tags:
    - rsyncd-logs
    - rsyncd-logrotate

- name: remove old logrotate file
  become: yes
  file:
    path: /etc/logrotate.d/rsync
    state: absent
  tags:
    - rsyncd-logs
    - rsyncd-logrotate

- name: rsyncd | selinux allow network connect
  become: yes
  seboolean:
    name: rsync_export_all_ro
    state: yes
    persistent: yes
  when: selinux_enabled

- name: rsyncd | start and enable service
  become: yes
  service:
    name: rsyncd
    enabled: yes
    state: started
