---
# tasks file for rsync-server

- name: rsyncd | install rsync
  become: yes
  yum:
    pkg: rsync
    state: present

- name: rsyncd | configure shares
  become: yes
  template:
    backup: yes
    dest: /etc/rsyncd.conf
    src: etc-rsyncd-conf.j2
    mode: '0400'
    owner: root
    group: root
  tags:
    - rsyncd.conf

- name: Create a directory if it does not exist
  file:
    path: "{{ item.path }}"
    state: directory
    #mode: '0755'
    #recurse: yes
    owner: "{{ item.uid | default('apache') }}"
    group: "{{ item.gid | default('apache') }}"
  loop: "{{ rsync_server_shares }}"
  tags:
    - dirs

- name: logrotate rsync logs
  include: logrotate.yml
  tags:
    - rsyncd-logs

- name: rsyncd | selinux allow network connect
  become: yes
  seboolean:
    name: rsync_export_all_ro
    state: yes
    persistent: yes
  when: selinux_enabled

- name: run rsyncd through xinetd
  include: xinetd.yml
  when: is_xinetd 
  tags:
    - xinetd

- name: rsyncd | start and enable service
  become: yes
  service:
    name: rsyncd
    enabled: yes
    state: started
  when: not is_xinetd 

