---

- name: xinetd | install rsync
  become: yes
  yum:
    pkg: xinetd
    state: present
  tags:
    - xinetd

#- name: logrotate.d/rsync & xinetd.d/rsync
- name: xinetd.d/rsync
  copy:
    backup: yes
    owner: "root"
    group: "root"
    mode: 0644
    src: "etc/"
    dest: "/etc/"
  tags:
    - xinetd

- name: enable xinetd
  service: name=xinetd  enabled=yes state=restarted
  tags:
    - xinetd

