---

- name: xinetd | install xinetd
  become: yes
  yum:
    pkg: xinetd
    state: present

- name: rsyncd | stop and disable service
  become: yes
  service:
    name: rsyncd
    enabled: no
    state: stopped
  ignore_errors: true

- name: xinetd.d/rsync
  template:
    backup: no
    owner: "root"
    group: "root"
    mode: 0400
    src: "etc-xinetd-rsync.j2"
    dest: "/etc/xinetd.d/"

- name: enable xinetd
  service: name=xinetd  enabled=yes state=restarted

